services:
  
  ai-rag: 
    image: ghcr.io/thewatergategroups/ai-rag
    command: python -m src.app
    depends_on:
      - mongodb
    volumes:
      - ./:/app
    network_mode: host
    env_file:
      - local.env

  mongodb:
    image: mongodb/mongodb-atlas-local
    # ports:
    #   - 27017:27017
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      # MONGODB_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: admin
      TZ: "Europe/London"
    network_mode: host
    volumes:
      # - mongo-db-data:/data/db
      # - mongo-db-config:/data/configdb
      - ./init-mongo/:/docker-entrypoint-initdb.d/
    env_file:
      - local.env

volumes:
  mongo-db-data:
  mongo-db-config: