services:
  
  ai-rag-template: 
    image: ghcr.io/treehousehl/ai-rag-template
    command: python -m src.app
    depends_on:
      - mongodb
    volumes:
      - ./:/app
    network_mode: host
    env_file:
      - local.env

  mongodb:
    image: mongo
    # ports:
    #   - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: admin
      TZ: "Europe/London"
    network_mode: host
    volumes:
      # - mongo-db-data:/data/db
      # - mongo-db-config:/data/configdb
      - ./init-mongo/:/docker-entrypoint-initdb.d/
    env_file:
      - local.env

# volumes:
#   mongo-db-data:
#   mongo-db-config: